name: Aprendiendo expression
run-name: ¡Primer hola mundo con expression!
on:
    workflow_dispatch:
        inputs:
            edad:
                description: 'Edad'
                required: true
                type: integer
            nombre:
                description: 'Tu nombre'
                required: true
                default: 'Oscar'
                type: string
jobs:
    mayor:
        if: ${{ inputs.edad >= 18 }}
        runs-on: ubuntu-latest
        steps:
            - name : Correr script
              run: echo ${{ inputs.nombre }} es mayor de edad
            - name: Correr python
              run: python hola_lenguaje.py     
    menor:
        if: ${{ inputs.edad < 18 }}
        runs-on: ubuntu-latest
        steps:
            - name : Correr script
              run: echo ${{ inputs.nombre }} es menor de edad
            - name: Correr python
              run: python hola-mundo.py