name: Aprendiendo secretos
run-name: ¡Primer hola mundo con secretos!

on:
  push: 
    branches: [ "main" ]
    
  schedule: 
    - cron: '59 23 * * SUN'
  
  workflow_dispatch:
    inputs:
        lenguaje_favorito:
            description: 'Lenguaje favorito'
            default: Python
            required: true
            type: choice
            options:
            - Python
            - JavaScript
            - Go
        nombre:
            description: 'Tu nombre'
            required: true
            default: Oscar
            type: string

env:
    SALUDO: hOLAAA

jobs:
  hola-mundo-manual:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Definir lenguaje
        run: echo "LANGUAGE=${{ inputs.lenguaje_favorito }}" >> $GITHUB_ENV

      - name: Correr python
        run: python hola_lenguaje.py

  hola-mundo:
    if: ${{ github.event_name != 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Definir secreto
        run: echo "$SALUDO, ${{vars.NOMBRE2}}, la contraseña es ${{secrets.CONTRA}}"

      - name: Definir variable
        run: echo "USERNAME=${{ vars.NOMBRE2 }}" >> $GITHUB_ENV

      - name: Correr python
        run: python hola-mundo.py