name: Saludo usando variables
run-name: ¡Primer hola mundo con variables!

on:
    push

env:
    DIA_DE_SEMANA: Lunes

jobs:
    saludo-variables:
        runs-on: ubuntu-latest
        env:
            SALUDO: Hola
        steps:
            - name: Saludar
              run: echo "$SALUDO, ${{ vars.NOMBRE }}. Hoy es $DIA_DE_SEMANA!"
            #   env:
            #     NOMBRE: Oscar